### ISSUE TITLE
Mobile version issue

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/RokoPhoto-Lite#17]
@rodica-andronache @claudiuvertistudio @ineagu am primit acest mesaj de la un client:

"Both myself and other visitors cannot load the theme on mobile devices. Tested with other mobile responsive themes and they work fine. Users just get a loading screen. Website is http://chrisbrowningblog.com using a self-hosted wordpress."

Eu am verificat site-ul lui si am aceasi problema pe iPhone. Nu se incarca, l-am lasat 2 minute si ramane la fel.

**Comment by claudiuvertistudio** [comment]
@rodica-andronache problema are legatura cu fisierul audio care trebuie sa se incarce pe pagina. Are 43.8MB ceea ce inseamna foarte foarte mult pentru un dispozitiv mobil.

**Comment by rodica-andronache** [comment]
@claudiuvertistudio ok, mersi
