### ISSUE TITLE
display text+tagline when logo is removed

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/RokoPhoto-Lite#2]
display text+tagline when logo is removed

**Comment by HardeepAsrani** [comment]
Can I use else if here?

And it's looking better without the tagline. What say?

**Comment by ineagu** [comment]
I think those are wp default settings right? Or we can display just title without tagline?

**Comment by HardeepAsrani** [comment]
Nope, those aren't required settings. Anyways, the theme already shows the title and tagline in the Sub-Header section, so even if it were a required settings, we already had it done.
