### ISSUE TITLE
footer in customizer

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/RokoPhoto-Lite#4]
The text from the footer : to get the latest etc should be added in customizer
In a new panel called footer along with social icons box
Copyright info should be also added in customizer and left aligned
On the right along the copyright we should have : RokoPhoto Lite powered by WordPress With links for theme name and Wp ( with nofollow attribute )

**Comment by HardeepAsrani** [comment]
Fixed the social links and added other sections.

@ineagu Having two sections in the footer copyrights isn't suiting the theme design. You can try adding one to a development site and it's looking odd. What say?

I still have to make footer copyrights customizable.

**Comment by ineagu** [comment]
then what do you think about RokoPhoto Lite powered by WordPress under the copyright ?

**Comment by HardeepAsrani** [comment]
Or maybe we can have...:

RokoPhoto Lite by ThemeIsle ~ Powered by WordPress

Which one so I can finish it right now? Also sent you a message on FB. :)

**Comment by ineagu** [comment]
AS I said we need to keep both user message like : mysite 2015, and ours...

**Comment by HardeepAsrani** [comment]
Let me see how two lines will look. Wait...
