### ISSUE TITLE
Add pinterest icon

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/RokoPhoto-Lite#40]
Maybe Add pinterest social profile icon to list? @rodica-andronache @claudiuvertistudio

**Comment by rodica-andronache** [comment]
@UVLabs if it's requested by many users we can add it (but also create the issue for the pro version) or else, I think you can suggest this doc http://docs.themeisle.com/article/104-adding-new-social-icons-to-rokophoto-footer

Let me know

**Comment by UVLabs** [comment]
@rodica-andronache I think the doc is adequate, closing.
