### ISSUE TITLE
Rokophoto Lite bugs 4.7

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/RokoPhoto-Lite#44]
- [ ] Social icons shows a "no-drop" icon when hovered over
- [x] Review button showing in sub controls: 
![image](https://cloud.githubusercontent.com/assets/10324144/20122461/3197baa0-a5ee-11e6-8455-e441a7fa5870.png)

  @rodica-andronache

**Comment by rodica-andronache** [comment]
@UVLabs thanks, for the second thing, I created a separated issue and we'll take care of it. But the first one, I didn't understood what you mean. I tested too and couldn't see anything. Can you please give more details?

**Comment by UVLabs** [comment]
@rodica-andronache create a simple html element and for the cursor property set it as "no-drop" you will see how the cursor appears.

Then on roko photo social icons hover over them and you should see the same cursor

**Comment by rodica-andronache** [comment]
@UVLabs for me , it's showing the pointer cursor on hover. I'm not sure how to replicate the issue. can you maybe send a gif or something?

**Comment by UVLabs** [comment]
@rodica-andronache try while in customizer gif doesnt show the mouse let me know if you're not seeing it while in customizer

**Comment by rodica-andronache** [comment]
@UVLabs ok, thanks I managed to see that. I created a separated issue for it.
