### ISSUE TITLE
Redo upsells like on shop isle

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/RokoPhoto-Lite#45]
- [x] Remove current upsells http://prntscr.com/d50q6l
- [x] Add a "Theme Info" section like Shop Isle with : (keep the strings exact the same they are now and the links like below)
      - View PRO version -> https://themeisle.com/themes/rokophoto/
      - Documentation -> http://docs.themeisle.com/article/137-rokophoto-documentation
      - Leave us a review(it will help us) -> https://wordpress.org/support/theme/rokophoto-lite/reviews/

- [x] At the bottom of customize, add the View PRO version like on shop isle http://prntscr.com/d50rf0
- [x] Remove all Frontpage sections http://prntscr.com/d50tyl
- [x] In Sub-Header section add the texts from all those Frontpage sections like:
Check out the PRO version add a Slider on frontpage!
Check out the PRO version add a Vision Slider on frontpage!
..
etc

Make sure you keep the same functions for translations like they are now.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu you left some 'oblique' occurrences in there :)

**Comment by cristian-ungureanu** [comment]
@rodica-andronache done, sorry
