### ISSUE TITLE
Social icons in footer on hover show "no-drop" type of cursor

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/RokoPhoto-Lite#49]
On WordPress 4.7
Only if the link for the social in complete, like http://www.google.com/

And only in customize

**Comment by UVLabs** [comment]
@HardeepAsrani says this might be a new feature @rodica-andronache @claudiuvertistudio so maybe you could check the release notes/commits to be sure

**Comment by HardeepAsrani** [comment]
@rodica-andronache It's happening on all outside links as you can't visit outside links when using Customizer, so it shows a unclickable mouse cursor, which is a feature. :)

**Comment by rodica-andronache** [comment]
ok, thanks for letting me know :)
