### ISSUE TITLE
Background image feature

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/RokoPhoto-Lite#50]
@rodica-andronache When you set a background image it doesn't show normally only while customizer is loading a new page, is this normal?

**Comment by rodica-andronache** [comment]
@UVLabs I don't understand what you say here :) can you please explain a little bit more?

**Comment by komakid** [comment]
I already wrote support on 6th Feb., had lots of mails, but they dot get it.

Since the Last Theme Update, the Background Picture isnt showing any longer, its just white now.
I became a code for (Additional CSS) but it was for the Header "Transpareny" and not for the "Menu", i would really appreciate if u can fix this, the wanted Look relies on the Background Picture, atm our site is just black and white...

thx hope to read from u soon

**Comment by abaicus** [comment]
@komakid Please leave a link to your website here so I can check it out. 

Have an awesome day!

**Comment by komakid** [comment]
Hi,
its gudrunbuechler.info

as u can see, background is all white, i think its showing trough on a few spots when ia turn up the brightness on my monitor but the transparency just isn’t was it was before

thx, hope u can give us a quick fix

best Abraham

**Comment by komakid** [comment]
this is the background image http://gudrunbuechler.info/wp-content/uploads/2016/09/Buchseite.jpg

**Comment by rodica-andronache** [comment]
Hi @komakid ,

Thank you for the details.
As a quick fix, you can add this custom css in Additional CSS:
`.blog {
     background: none !important; 
}`
Please let me know if this helps.

Regards,
Rodica

**Comment by komakid** [comment]
Ok, thx this works for the pages, but unfortunately not for the Startpage !?

**Comment by komakid** [comment]
do u have a similar code for the "Navigation" Menu / Startpage for us !? thx

**Comment by komakid** [comment]
Anyone !? tried everything what i could find within inspector, but nothing worked so far...

**Comment by abaicus** [comment]
Hello @komakid. What @rodica-andronache meant to write was `div.blog { background: transparent !important; }`. This should work out fine.

Have an awesome day!

Andrei.

**Comment by komakid** [comment]
THX THX THX :))) IT WORKS !!!

**Comment by abaicus** [comment]
Glad we could help! 👍

**Comment by komakid** [comment]
But still curious why this happened after the last update ;)
