### ISSUE TITLE
Issues with comments

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/RokoPhoto-Lite#52]
- Comments counter are not working
- Time format can't be change
- Errors 

![knipsel](https://cloud.githubusercontent.com/assets/9929553/23894609/794db46a-08ab-11e7-94d2-9e907a229109.JPG)
![screenshot_1](https://cloud.githubusercontent.com/assets/9929553/23894610/7962b2ac-08ab-11e7-8c21-154e532b9695.png)

**Comment by rodica-andronache** [comment]
@cristian-ungureanu thanks for reporting the issue. RokoPhoto Lite is now generated from RokoPhoto , so this repo is not used anymore. If you have any other stuff to report please do it here https://github.com/Codeinwp/RokoPhoto
