### ISSUE TITLE
Issue with Loco Translator

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/RokoPhoto-Lite#55]
@rodica-andronache  I have added this issue here: 

"For example, I translated 2 strings using Loco Translate. They are: "Your Message" and "Your Message *". If you're able to login to my admin area using pirate parrot, you'll see those strings. However on the front end (www.gazibilgisayar.com.tr) the text "Your Message" is still there, it isn' translated. "

@HardeepAsrani already tested and the issue exists. Let me know if we can fix this bug.

The ticket link: https://secure.helpscout.net/conversation/367591114/133593/?folderId=212385

**Comment by rodica-andronache** [comment]
@mileamadalin this is the repo for both RokoPhoto and RokoPhoto Lite https://github.com/Codeinwp/RokoPhoto so all issues should be added there.

And for the problem, I don't think we'll add translation compatibility for free products, so we'll not fix this.
If the same problem, is in the pro theme, you can let me know,  and we'll fix it at some point :)
