### ISSUE TITLE
theme check suggestions

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/RokoPhoto-Lite#8]
Here they are, try to fix if is something relevant : 

RECOMMENDED: This theme contains no sidebars/widget areas. See Widgets API
RECOMMENDED: Text domain problems in functions.php. You have not included a text domain!
RECOMMENDED: could not find the file readme.txt in the theme. Please see Theme_Documentation for more information.
RECOMMENDED: No reference to add_editor_style() was found in the theme. It is recommended that the theme implement editor styling, so as to make the editor content match the resulting post output in the theme, for a better user experience.
INFO: Non-printable characters were found in the functions.php file. You may want to check this file for errors.
INFO: Non-printable characters were found in the footer.php file. You may want to check this file for errors.

**Comment by ineagu** [comment]
@HardeepAsrani any news on those ? is your hand better ? :)

**Comment by HardeepAsrani** [comment]
Noting to see here. :)
